

[mongo]
uri = "mongodb+srv://neminharia_db_user:SGP5@cluster0.ddhnapz.mongodb.net/?retryWrites=true&w=majority"

[gemini]
api_key = "AIzaSyAhJ-ZeehyQnge_Qy8rBAuU7shpekfzgQI"

[ocr]
tesseract_cmd = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"